### PR TITLE
Ping passthrough

### PR DESCRIPTION
**Pull request by astei**
A more general (and flexible) version of #239.

### CODE REVIEW

**Comment by astei** [comment]
Tested with passthrough disabled and with forwarding all information. Mod-only forwarding will be tested as soon as I'm back in college.

**Comment by Leymooo** [comment]
Why ping all servers instead of first server in list like in bungee?

**Comment by astei** [comment]
Because there is no reason not to parallelize the work in question. This will speed up the response to the user if a server is slow in responding to the request by allowing all the other requests to go through.

This is also required for the mods-only pass-through to work: it has to find the first server with a mod list it can pass to the client.

**Comment by LGCMcLovin** [comment]
what if first server is a lobby with no mods, and you want a specific set of servers to be checked?

**Comment by astei** [comment]
It will try to pick the first mod list it finds. So if you have a vanilla server first, it will move onto the next item in the list, because it has no mod list.

**Comment by astei** [comment]
Mod list forwarding works. I am merging this in.

**Pull request merged**
