### PR TITLE
An Easter basket bearing gifts!

### PR DESCRIPTION
**Pull request by astei**
It's been a while since I've been tackling major Velocity issues. After much work, I'm finally able to present a nice Easter basket full of gifts for Velocity users:

* Velocity will now wait until `JoinGame` is sent before actually initiating a server switch. (Should fix a number of issues such as #183).
* Velocity is now using Gradle 5!
* A number of nits have been fixed thanks to the switch to Error Prone that accompanied the switch.

Issues left to look at:

* ~~What if Forge connection fails?~~

### CODE REVIEW

**Comment by dualspiral** [comment]
> What if Forge connection fails?

Once the Forge handshake has started, the client reverts to a frozen state so as far as it is concerned, it should not be receiving any packets from the old server. It also should not be receiving most packets from the new server until the handshake has completed, such as position and rotation packets. The only safe thing to do at that point is to kick the client if the handshake fails.

**Comment by astei** [comment]
Good to know. I'm wondering if there exists any early cases where Velocity can possibly recover. Can you reset the Forge handshake while it is still handshaking?

**Comment by dualspiral** [comment]
> Can you reset the Forge handshake while it is still handshaking?

No, it only accepts the reset packet during the `DONE` state - https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeClientState.java#L200

I am unsure of if there is a way to ask the client if a modlist is good without the handshake. I looked into how the server list works, it's all client side. We may be stuck here, unfortunately.

**Comment by astei** [comment]
Very well then. We can only hope for something better in Forge 1.13.

**Pull request merged**
