### PR TITLE
Allow to edit GameProfile properties.

### PR DESCRIPTION
**Pull request by Leymooo**
Can be useful for skin change plugins

### CODE REVIEW

**Comment by Cybermaxke** [comment]
The player will have to be respawned (includes sending tab list packets, etc.) on the client in order to update its skin.

**Comment by Leymooo** [comment]
i know this. I make this to avoid using a reflection in plugins.

**Comment by DoNotSpamPls** [comment]
Usually skin plugins circumvent this by vanishing and unvanishing the player instantly.

**Comment by theminecoder** [comment]
The problem with this sort of functionality is unless you're only running one proxy, you need to replicate this change to any other proxy instance that may or may not use the profile at some point. This sort of stuff really should be left to the server level so the proxy doesn't need to special case data for some specific players.

**Comment by astei** [comment]
I think @Cybermaxke is right, and his reasoning is the same reason why I'm leaning towards not including this in Velocity. Either way, you still need to handle the skin switching on the server-side, and if you've already got code to handle that, what is Velocity doing other than providing a very small convenience?

**Comment by Cybermaxke** [comment]
Maybe can the field be internally updated by tracking packets send from the server? I don't see why you would manually modify it.

**Comment by astei** [comment]
That's just extra complexity for what is ultimately a niche feature in my opinion. Velocity can not reasonably cater to 100% of users by being everything to everyone. That sets us up for disaster and will almost certainly lead to Velocity 2.0.0 being a thing within months.

**Comment by Cybermaxke** [comment]
That's true, @Leymooo what is the reason that this should be updated in the proxy, instead of it being kept to server level?

**Comment by Leymooo** [comment]
Check the  ChangeSkin plugin. It uses a reflection to update a field with properties. I thought it could be good to allow change the properties via api.

@Cybermaxke plugins need to update properties on proxy, in order to send a changed skin data to others servers on switch and spawn player using new properties. If plugin dont change the propertis, plugin need to send a new skin data via PM or smth and respawn player again after player was spawned on server after switch.

**Comment by astei** [comment]
I'm leaning towards merging this now. Please rebase on upstream.

**Comment by astei** [comment]
Thanks!

**Pull request merged**
