### PR TITLE
Send only one respawn packet on server switch

### PR DESCRIPTION
**Pull request by Leymooo**
We can simply set dimension in JoinGame packet and send only one respawn packet. Useless, but why not?

### CODE REVIEW

**Comment by dualspiral** [comment]
Fairly sure that this would break mods, with this, the client and server may not be in sync with the dimension ID (client might think ID -1, while the server might think ID 0), and so any client/server mod combo that relies on that will fail.

You could get away with only sending two packets if the incoming ID is the same as the outgoing one.

**Comment by Leymooo** [comment]
Why it should break mods? Velocity send 2 respawn packets to clear chunk cache(first with different dim and second with joinGame dim), this will trigger a world loading screen and clear chunk cache.

My pr also will trigger world loading screen and will clear chunk cache.

Just some code from MC.
```java
    public void handleJoinGame(SPacketJoinGame packetIn)
    {
        ....
        this.gameController.player.dimension = packetIn.getDimension();
        ....
    }
    public void handleRespawn(SPacketRespawn packetIn)
    {
        ...
        if (packetIn.getDimensionID() != this.gameController.player.dimension)
        {
              //some code to clear chunk cache and show world loading screen.
        }
       ...
    }
```

**Comment by dualspiral** [comment]
Ok, sure. I don’t have my MCP workspace to hand to look at the specifics, though mods do funny things that no one ever expects. It would make sense to test this with a modpack or two to ensure compatibility. I would also assume that this is the same behaviour since 1.8.

My comment was otherwise valid for the code as it stood so was not totally baseless, (the wrong ID was being used in the response packets and thus was the original reasoning for my comment, even if my ultimate statement was wrong), but I see that’s been rectified now so no harm done.

**Comment by astei** [comment]
You might want to update the comment.

If this is safe I'm fine with merging this in.

**Comment by astei** [comment]
Closing due to inactivity.

**Pull request closed without merging**
