### PR TITLE
Remove protocol linking

### PR DESCRIPTION
**Pull request by Leymooo**

### CODE REVIEW

**Comment by astei** [comment]
Has this been tested? What benefits can we expect from this (i.e. lower memory usage)?

**Comment by astei** [comment]
I see. Much less duplication if a packet ID hasn't changed. I'm fine with this.

**Comment by Leymooo** [comment]
I tested a join from 1.8, 1.12.2 and 1.14.2 before create a pr. If you want i can test it more, but i sure it should be ok.

**Comment by astei** [comment]
I think that's fine. I'll merge this in.

**Pull request merged**
